name: Update HTML

on:
  push:
    paths:
      - 'tweet_urls.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: amznlink/X-Animal-Posts
        FILE_PATH: tweet_urls.txt
      run: |
        python generate_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add embedded_tweets.html
        git commit -m 'Update embedded tweets HTML'
        git push
